version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

terraform_versions: &terraform_versions
  - 1.3.0
  - 1.4.0
  - 1.5.0
  - 1.6.0
  - 1.7.0
  - 1.8.0
  - 1.9.0

terraform_folders: &terraform_folders
  - ./

workflows:
  validate:
    jobs:
      - terraform/fmt:
          checkout: true
          recursive: true
      - terraform/validate:
          checkout: true
          backend: false
          matrix:
            parameters:
              tag: *terraform_versions
              path: *terraform_folders
